services:
  db:
    build: ./db                     
    platform: linux/amd64
    container_name: postgis-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./backend/gisdata:/gisdata
      - ./backend/gisdata/import_shapes.sh:/docker-entrypoint-initdb.d/import_shapes.sh
    networks:
      - app-network

  fastapi:
    build: ./backend
    container_name: fastapi-backend
    # ports:
    #   - "8000:8000"
    expose:            # (Optional) ระบุไว้เพื่อบอกว่า container นี้เปิด port นี้สำหรับ internal network
      - "8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  webapp:
    build: ./frontend
    container_name: angular-webapp
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgis_data: